apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: log-pod
  name: log-pod
spec:
  containers:
  - image: busybox:latest
    command: ["echo", "Hello, I am the first container nice to meet you."]
    name: first
  - image: busybox:latest
    command: ["echo", "Hello, I am the younger container my name is second."]
    name: second
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure

